#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CustomHeader_Android.Resource", IsApplication=true)]

namespace CustomHeader_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Com.Syncfusion.Schedule.Resource.Drawable.arrow_down = global::CustomHeader_Android.Resource.Drawable.arrow_down;
			global::Com.Syncfusion.Schedule.Resource.Drawable.arrow_up = global::CustomHeader_Android.Resource.Drawable.arrow_up;
			global::Com.Syncfusion.Schedule.Resource.Drawable.Recurrence = global::CustomHeader_Android.Resource.Drawable.Recurrence;
			global::Com.Syncfusion.Schedule.Resource.String.No_Appointments = global::CustomHeader_Android.Resource.String.No_Appointments;
			global::Com.Syncfusion.Schedule.Resource.String.all_day = global::CustomHeader_Android.Resource.String.all_day;
			global::Com.Syncfusion.Schedule.Resource.String.library_name = global::CustomHeader_Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_down = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_up = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Recurrence = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int customHeader = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int schedule = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int No_Appointments = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int all_day = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int app_name = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int hello = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
